apiVersion: v1
kind: Namespace
metadata:
  name: envoy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoy
  namespace: envoy
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
  namespace: envoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy
  namespace: envoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: envoy
subjects:
  - kind: ServiceAccount
    name: envoy
    namespace: envoy