apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-initializer
  namespace: envoy
data:
  config: |
    containers:
      - name: envoy
        image: registry.cn-hangzhou.aliyuncs.com/morse_k8s/envoy:845747db88f102c0fd262ab234308e9e22f693a1
        command: ["/usr/local/bin/envoy"]
        args:
          - "--concurrency 4"
          - "--config-path /etc/envoy/envoy.json"
          - "--mode serve"
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        volumeMounts:
          - name: envoy-conf
            mountPath: /etc/envoy
    volumes:
      - name: envoy-conf
        configMap:
          name: envoy
---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-init-svc-tls
  namespace: envoy
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVKVENDQXcyZ0F3SUJBZ0lVUGdZYmVrbDE3VEo1MlE4b2hTSTdvU1B4Q2FFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JqRU9NQXdHQTFVRUJoTUZRMGhKVGtFeEVEQU9CZ05WQkFnVEIxTklRVUZPV0VreERUQUxCZ05WQkFjVApCRmhKUVU0eEV6QVJCZ05WQkFNVENtdDFZbVZ5Ym1WMFpYTXdIaGNOTWpFd016RXdNRGsxTlRBd1doY05Nakl3Ck16RXdNRGsxTlRBd1dqQkdNUTR3REFZRFZRUUdFd1ZEU0VsT1FURVFNQTRHQTFVRUNCTUhVMGhCUVU1WVNURU4KTUFzR0ExVUVCeE1FV0VsQlRqRVRNQkVHQTFVRUF4TUtaVzUyYjNrdGFXNXBkRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXdwS1lWTHdRdEd0OVR1NU9MS2hJczZyMjRVWkg5alV5M1ErTmZ1CktPTlU3WG9GZ1doaUxiOUtoNzhKdndDTlpUUkpVVCtyaE04Vm9qbkRrRGk4S2lURDN0SndkMmdJM3A5TjRqa2IKa1R4SHI4eUNpOWVNTFVkWENVSTdxOHBvWTlkcGI2cTFEU1FndHFncW9zY0tqR1ZzWU5lamh5SXlvaUFYOGdKQgpuQklCMUMxdW5UMWQrcTM0WEZ6alNTbEYvL3hLcEhnVHIyZUtsQWZ4c0xwbGtySzBHaXlwRXAvazF2ZzRNVGF6CjkrZHdxcGVhY2J2T3REK0hXZTZYWjZVZjg3UjRYM2p5cDZwYUE4Tlk3UEZuc0ZvMFMweWp6REJWVzc4b0ZIbW4KelgvT05ZcjZOS2xReHJxOHk4ZUZNbC85ZTQrQ20wb2oxSWFnUXNHb1Mra0kvT0VDQXdFQUFhT0NBUWt3Z2dFRgpNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3CkRBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVUFA2a3pwdjN5RENhSVA1QmFRaFNQNThwc0xvd0h3WUQKVlIwakJCZ3dGb0FVOXFRbWt4QWVSd0poYmV2L2U1MjBrenV0cVFBd2dZVUdBMVVkRVFSK01IeUNDbVZ1ZG05NQpMV2x1YVhTQ0VHVnVkbTk1TFdsdWFYUXVaVzUyYjNtQ0ZHVnVkbTk1TFdsdWFYUXVaVzUyYjNrdWMzWmpnaHhsCmJuWnZlUzFwYm1sMExtVnVkbTk1TG5OMll5NWpiSFZ6ZEdWeWdpSmxiblp2ZVMxcGJtbDBMbVZ1ZG05NUxuTjIKWXk1amJIVnpkR1Z5TG14dlkyRnNod1IvQUFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTRZZGxoeHFlSQphTWZmNTVZblhxTDBDTzl0ODduV09JbEdKRHlhSTlxRzhQOVZieUtmR1EweFhTcVYvZTl5R3pHUFRYaHNSUENECkRnRFc2QkQrM050ZVRqYkFGNDNkeVBqaDF5UlZkSFE3SHRWT2hWRTMxTG9vZXg3cjZUWVZKQkpXR3hUQjMvbTYKNkV0QVBKUWFWMHF2SnlJcUdQVDA4MVdWZ0NiR3BGT1BObjl4OHJUb0owRXhyU3R0WkVDZHgvbTNLWHNSL1pYbwpHaWwzenNSa2FMdWgxVDZ6bko5elgrVm1vVGdzYkRPZlNYcmtQTkNEQzFVL3AwVGxvSzBXdUlmTE9jZUk1R0UyCklnSG8xQTJxSmhUVW5EMHFtZVdQUFNmL3VuazJJbmxQY1RobGxFUjJIY3ppYlFGeUZsQVhTcXRoa044VnF5SmIKVVF3Rkxwc21zczZnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBekNrcGhVdkJDMGEzMU83azRzcUVpenF2YmhSa2YyTlRMZEQ0MSs0bzQxVHRlZ1dCCmFHSXR2MHFIdndtL0FJMWxORWxSUDZ1RXp4V2lPY09RT0x3cUpNUGUwbkIzYUFqZW4wM2lPUnVSUEVldnpJS0wKMTR3dFIxY0pRanVyeW1oajEybHZxclVOSkNDMnFDcWl4d3FNWld4ZzE2T0hJaktpSUJmeUFrR2NFZ0hVTFc2ZApQVjM2cmZoY1hPTkpLVVgvL0Vxa2VCT3ZaNHFVQi9Hd3VtV1NzclFhTEtrU24rVFcrRGd4TnJQMzUzQ3FsNXB4CnU4NjBQNGRaN3BkbnBSL3p0SGhmZVBLbnFsb0R3MWpzOFdld1dqUkxUS1BNTUZWYnZ5Z1VlYWZOZjg0MWl2bzAKcVZER3Vyekx4NFV5WC8xN2o0S2JTaVBVaHFCQ3dhaEw2UWo4NFFJREFRQUJBb0lCQVFDcEhKZUdFSC94WlR5MQpKc1YxanFkSDVPNlgwbENFckxPanlldTJnVkpoTEdJaHB4blFhekxWdDFqR1I3NXRLTEppSXpFbitsMWlZOXNpCjJmbEc1YVpMR2V3aWlJS0FMSWlya0lvSkgrcW44Z0dPOTd2NmFlUy9xVHJFSUVWbXZoMmx1M0tDQnNMQjRFOHMKOFZRd1oyNXdQTnZqQTFQV1lmYWxldkErS2phck9sbU03LzZWYXZ5RTdYOUxjWURRTmxSRndGNzdwM0JxdnJSNQoyZzl6ZDJvUS84Uk53eU96Nmk0MEJvQ2ZjWGR3SGc2SWk5RjcxRWlLNFVmckN5dVI2NGJHTFRhWGRlQmR1NmMvCnJqV3h3aXRqa1NvRUwvQVh6K0ppQnhGYXUwRFlxcWpsUDZWOTRHM2Z5SlN6VHhiOGIrRHlzUEtRM1ZFaTNDVTcKZWFTeHhLaTVBb0dCQU8yMi9lUGNGRmJCRXYveHpSK3d2eDZ5OS9QK2Nick1pdGc2KzIxbFB6R3dLb0NTMlBRMwowamJnSTRsNWpZNVZLUWpGK0ZWNm9oOC9WQWwxb0xyZlUrNUZqaTllV3RTWmZ6ZWQwS1dkazhOVWRYNUx0Y2JDCjF3M1F5NlpCbE1FUEN5YWNxMzF1RVN3SXR3L2xHS2N6VVRYMHZXcThxa1lMUnBsSnFuRkt1ay9mQW9HQkFOdmQKYjAxZmVDcVcwdC9KSCtUbFA0YzViL0ZIYjZEbVY1ZUxEN1FBLzJ0a1h4MC9reUNxUmZFWFVEc3NPL01wRjZRegp4RU1GRTluT3g3SmpuV2w1T2dTVGpteklmVWp6empPa1ZSWlVyODZnT01NSm5jNENYRm1aS3l3dUwvTGtEaWQ3ClNaVGRmWEJGZVFnMjMvbUkrYWtWN1h3U1lBUVhtS29HNTBpVlYwcy9Bb0dBTUFyRW94RnVkdDRNZGZlcmFoVXgKZXdYV2dOUlNyZHI2MEpxVEI5Zm5mcVpJNExWTTdZWitrS0taN0FYSjZ4TWcrT254dDJ6U2FSaEdacWNFTmVBKwp1VEFMZlYxSFpDSWxpTnIzT1JGd3RKQlVNcE1naUt3R0JIL0hPTEdXVzdJcm9jRVdFNEowSy84UzZENTN6Z3JjCkJkaVJrNG5QcTlwSmlWOU8rQmlQTU9jQ2dZQlhoR28waTBjQzlPeFZwZkpySTVISkd1VGpUd014TWQ4MTlHVzQKeWhqaHY1OVl2aUNyaFB1NFB3Wnh0MmJab01iSFZzL051YXl3SzI0MEpSRFlsaWV4QUtkVngreU82SFZ3K3YzZgptTEF1ZUhwL3NFay9ZcE11R3hralNmTk9KTmM1Z2dyRkZmRkRpblBtQUNuaFkxTzFxWVBSdW1LNzNrU25rWDNvCjE0RmE4d0tCZ0FsRkZzdDQzTzRzRVdSaXIvcG81Vm41YktMM2JLRUJvSi9Jdy9pTVFzRWJBaStidmEwN1NQRHEKZlNzTzB4V0pCNG9zK1FBY1dhU1FLb2VTOTYwNjQyVUVDSUZUdFQ1N0xxd0NJajA3S29GR3FPQU16NjRML0phSQplaC9DMFFWcW5UM0FMNnlHYUtMTU1haEw1Y1BPMDRmeHRydmkrNktSdUdPcG9EZkpRZ0FJCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
