apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy-initializer
  name: envoy-initializer
  namespace: envoy
spec:
  selector:
    matchLabels:
      app: envoy-initializer
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy-initializer
      name: envoy-initializer
    spec:
      serviceAccountName: envoy
      containers:
        - name: envoy-initializer
          image: registry.cn-hangzhou.aliyuncs.com/morse_k8s/envoy-init:0.1.0
          imagePullPolicy: Always
          args:
            - "-annotation=initializer.kubernetes.io/envoy"
            - "-require-annotation=true"
            - "-tls-cert-file=/etc/tls/tls-crt.pem"
            - "-tls-private-key-file=/etc/tls/tls-key.pem"
          volumeMounts:
            - mountPath: /etc/tls
              name: tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: envoy-init-svc-tls
            items:
              - key: tls.crt
                path: tls-crt.pem
              - key: tls.key
                path: tls-key.pem
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-init
  namespace: envoy
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: envoy-initializer