apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: envoy-initializer
  labels:
    app: envoy-initializer
webhooks:
  - name: envoy.fuxiao.dev
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 10
    clientConfig:
      service:
        name: envoy-init
        namespace: envoy
        path: "/envoy-init"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQWtTZ0F3SUJBZ0lVRk1NT2o4ZjAxNk5RazduY0Y0VkVtdFJkZ3JBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JqRU9NQXdHQTFVRUJoTUZRMGhKVGtFeEVEQU9CZ05WQkFnVEIxTklRVUZPV0VreERUQUxCZ05WQkFjVApCRmhKUVU0eEV6QVJCZ05WQkFNVENtdDFZbVZ5Ym1WMFpYTXdIaGNOTWpFd016RXdNRGsxTXpBd1doY05Nall3Ck16QTVNRGsxTXpBd1dqQkdNUTR3REFZRFZRUUdFd1ZEU0VsT1FURVFNQTRHQTFVRUNCTUhVMGhCUVU1WVNURU4KTUFzR0ExVUVCeE1FV0VsQlRqRVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekNDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0pMQTVjREhRV1RBVVIzdW5ZYU41WDBRZ1VodFE2RnlwQU0wWnFPCmx3dm1QdGZoNXREL1pGQUMwLzZJdUp2a2ZTdjQxeS9OemRCdHExbkRSaDNMdjNUV2gzUWJmblFuYUwxOTFTQnQKZjZCUExkYnZ1WGRRalZ3TXRXVk1SYm9hRTFMVm83UElsYnh6ZnlUV2RBeDFaUy84cnI3MDZ2eUJKenh6K2hPdwpHejhoNkwrNy9IMEE5NjI5aFJmNllMWk05VW00N09WNGRncUQxbS9nc0dwVzNmNlU0L1hEejNXTTRlcnBrWmZXCjk4aW5FTTV0ZzNyeVI2alBVeEozSVRjUVBOdHN1UzlRc1loR3FkQjRYWTRmUUIzZUliUHk2SS8vdytCMGRGUmEKajZNbXBsL3ROVm45WUNhYkVPSmR5VUFYWkczNHZpRlZwM3llUVdlZnUwaHVsMjBDQXdFQUFhTkNNRUF3RGdZRApWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlBha0pwTVFIa2NDCllXM3IvM3VkdEpNN3Jha0FNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNEQjhraW5Panlpdm8rUE9NTkMvMWIKeXRiNkpBUTRKbFFNSC9oMTJEZ1pqNU1ucjdOQ2w3azB6Yll6d051WEJ5UHZWWGZxV0Rja0hna05ucWVLYmQ2cwozTEp4MEorSkdWQUhHRm9hQ1hmdUw2SnpTTnE0cCtQbndmb1J6SHpOUE1mOElSclUvT3B2T2JwY2JZRWJNTWlJCkJMSGdEUThOMDhDYW9KWkVWRlgvY29jYzNkUVRSTEx5T21zSXdWWEgxcWlMcExpODNEQ3JKcVdvSEczeDJxSGsKRFdSN2kyeHh6SnZIdkxreUUwMjdHSjlEeVpMc2Jxb0NvbEZuTFJHTEErV2FFQWcrblcxS2hSd2owbWxQVEdKUwpQU2FVYTRiTVAzRTlTWFFvSnRERTk2SXpzS1lEOTJubE9Qak5POGNibWIxY0ZQZjZ4SCszdlFHZlhwMnJaWEZ4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["*"]
        resources: ["deployments", "pods"]
        scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
