apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/morse_k8s/helloworld:0.1.0
          name: app
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-app